spring:
  application:
    name: kafka-notification
  datasource:
    url: jdbc:h2:mem:kafka-notification
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /console
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create